global_testa_config = {
    "ta-rb": {
        "outputMethod": "puts",
        "commentStartBy": "#",
        "tryCatch": "try: \n\t **** \nexcept Exception as es \n\t puts(es)",
        "function": "def ",
        "varDeclaration": "",
        "classInstantiationNew": "",
        "AccoladeStart": "",
        "AccoladeEnd": "\n end",
        "NoneNull": "None",
        "selfOrThis": "self",
        "selfOnFunctionParams": True,
        "semicolon": "",
        "scriptStarter": "",
        "scriptEnd": "",
        "prefixVariable": ""
    },
    "ta-py": {
        "outputMethod": "print",
        "commentStartBy": "#",
        "tryCatch": "try: \n\t **** \nexcept Exception as es: \n\t print(str(es))\n",
        "function": "def ",
        "varDeclaration": "",
        "classInstantiationNew": "",
        "AccoladeStart": ":",
        "AccoladeEnd": "",
        "NoneNull": "None",
        "selfOrThis": "self",
        "selfOnFunctionParams": True,
        "semicolon": "",
        "scriptStarter": "",
        "scriptEnd": "",
        "prefixVariable": ""
    },
    "ta-php": {
        "outputMethod": "print",
        "commentStartBy": "//",
        "tryCatch": "try{ \n\t **** \n}catch(Exception $e){ \n\t print($e);}",
        "function": "function ",
        "varDeclaration": "$",
        "classInstantiationNew": "new ",
        "AccoladeStart": "{",
        "AccoladeEnd": "}",
        "NoneNull": "null",
        "selfOrThis": "$this",
        "selfOnFunctionParams": False,
        "semicolon": ";",
        "scriptStarter": "<?php \n",
        "scriptEnd": "\n ?>",
        "prefixVariable": "$"
    },
    "ta-js": {
        "outputMethod": "console.log",
        "commentStartBy": "//",
        "tryCatch": "}try{ \n\t **** \n}catch(err){ \n\t console.log(es);}",
        "function": " ",
        "varDeclaration": "var ",
        "classInstantiationNew": "new ",
        "AccoladeStart": "{",
        "AccoladeEnd": "}",
        "NoneNull": "null",
        "selfOrThis": "this",
        "selfOnFunctionParams": False,
        "semicolon": ";",
        "scriptStarter": "",
        "scriptEnd": "",
        "prefixVariable": ""
    }
}
